// GENERATED by scripts/gen-capabilities.cjs — do not edit by hand.
// Regenerate with: node scripts/gen-capabilities.cjs
// Derived from core/capabilities/protocols.json (shared with the Go backend).
// Each list is used as a set membership test; order is not significant.

export const inboundWithUsers: string[] = ['socks', 'http', 'mixed', 'shadowsocks', 'vmess', 'vless', 'trojan', 'naive', 'hysteria', 'hysteria2', 'tuic', 'anytls', 'shadowtls', 'mieru', 'trusttunnel', 'ssh', 'mtproxy']
export const HasInData: string[] = ['socks', 'http', 'mixed', 'shadowsocks', 'vmess', 'vless', 'trojan', 'naive', 'hysteria', 'hysteria2', 'tuic', 'anytls', 'shadowtls', 'mieru', 'sudoku', 'trusttunnel', 'ssh']
export const HasTls: string[] = ['http', 'vmess', 'vless', 'trojan', 'naive', 'hysteria', 'hysteria2', 'tuic', 'anytls', 'trusttunnel']
export const MuxAvailable: string[] = ['shadowsocks', 'vmess', 'vless', 'trojan']
export const OnlyTLS: string[] = ['naive', 'hysteria', 'hysteria2', 'tuic', 'anytls']
